### ISSUE TITLE
[PROPOSAL] Rename to cbfs

### ISSUE THREAD

**Issue by elpete** [coldbox-modules/cbfiles#1]
Fee free to close this if you don’t like the name. I just thought `cbfs` had a nice ring to it like it was a filesystem format. 🙃

**Comment by jclausen** [comment]
I like it!  Short and sweet! ☺

**Comment by lmajano** [comment]
Ok will do.

I wanted to keep this a secret and showcase it to y’all but you got me :)

Luis Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.com
P/F: 1-888-557-8057

________________________________

**Comment by jclausen** [comment]
I didn't see anything...! 😄
